apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: $APP_NAMESPACE
type: Opaque
data:
  mysql-root-password: $DB_ROOT_PASS    # Test@123
  mysql-database: $DB_NAME              # bankappdb
  mysql-user: $DB_USER                  # root

