apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankapp
      version: v1
  template:
    metadata:
      name: bankapp
      labels:
        app: bankapp
        version: v1 
    spec:
      containers:
      - name: bankapp
        image: chinmayapradhan/bankapp:4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: db_user
              name: db-secret
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_root_pwd
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
