apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
  namespace: $APP_NAMESPACE
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bankapp
    version: blue # This can be changed to "green" when switching traffic
