apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: webapp
data:
  db_server: jdbc:mysql://mysql-0.mysql:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true