apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: my-app
data:
  spring.datasource.url: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true