apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: webapp
  labels:
    app: java-app 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: chinmayapradhan/bankapp:1.0
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              key: db_server
              name: db-config
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: db_user
              name: db-secret
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db_root_password
              name: db-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: webapp
spec:
  selector:
    app: java-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

            

# kubectl rollout restart deployment java-app-deployment -n webapp  -- restart the pod
# kubectl rollout undo deployment java-app-deployment -n webapp -- undo the last rollout
# kubectl rollout history deployment java-app-deployment -n webapp -- show the rollout history
# kubectl exec -it mysql-0 -n webapp -- df -h | grep /var/lib/mysql -- check the disk space
# kubectl exec -it mysql-0 -n webapp -- du -sh /var/lib/mysql -- check the size of the mysql data directory
# kubectl -n webapp exec -it java-app-deployment-ccc4b6c75-c87pl -- wget -q -O - http://localhost:8080/login -- check the health of the java app
# kubernetes]$ kubectl run mysql-client -it --rm --restart=Never --image=mysql:8 -n webapp -- mysql -h mysql -u root -pTest@123 -- check the mysql connection
# kubectl -n webapp describe pod mysql-0 | grep -A10 "Mounts" -- check the mounts
# kubectl get endpoints java-app-service -n webapp -o wide -- check the endpoints
 